/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely'

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>

export type Int8 = ColumnType<
  string,
  bigint | number | string,
  bigint | number | string
>

export type Json = JsonValue

export type JsonArray = JsonValue[]

export type JsonObject = {
  [x: string]: JsonValue | undefined
}

export type JsonPrimitive = boolean | number | string | null

export type JsonValue = JsonArray | JsonObject | JsonPrimitive

export type Timestamp = ColumnType<Date, Date | string, Date | string>

export interface _Migrations {
  created_at: Generated<Timestamp>
  id: Generated<number>
  name: string
}

export interface Attachments {
  created_at: Generated<Timestamp>
  file_size_bytes: Int8
  file_type: string
  filename: string
  id: Generated<string>
  organization_id: string
  storage_path: string
  task_id: string
  user_id: string
}

export interface AuditLog {
  action: string
  created_at: Generated<Timestamp>
  id: Generated<Int8>
  organization_id: string | null
  payload: Json | null
  user_id: string | null
}

export interface Comments {
  body: string
  created_at: Generated<Timestamp>
  id: Generated<string>
  organization_id: string
  task_id: string
  user_id: string
}

export interface Organizations {
  created_at: Generated<Timestamp>
  id: Generated<string>
  name: string
  updated_at: Generated<Timestamp>
}

export interface Projects {
  created_at: Generated<Timestamp>
  created_by_id: string
  id: Generated<string>
  name: string
  organization_id: string
  updated_at: Generated<Timestamp>
}

export interface Sessions {
  created_at: Generated<Timestamp>
  expires_at: Timestamp
  id: Generated<string>
  user_id: string
}

export interface ShareTokens {
  created_at: Generated<Timestamp>
  created_by_id: string
  expires_at: Timestamp | null
  id: Generated<string>
  organization_id: string
  project_id: string
  token_hash: string
}

export interface Tasks {
  created_at: Generated<Timestamp>
  created_by_id: string
  id: Generated<string>
  organization_id: string
  project_id: string
  status: Generated<string>
  title: string
  updated_at: Generated<Timestamp>
}

export interface Users {
  created_at: Generated<Timestamp>
  email: string
  id: Generated<string>
  password_hash: string
  salt: string
  updated_at: Generated<Timestamp>
}

export interface UsersOrganizations {
  organization_id: string
  role: Generated<string>
  user_id: string
}

export interface DB {
  _migrations: _Migrations
  attachments: Attachments
  audit_log: AuditLog
  comments: Comments
  organizations: Organizations
  projects: Projects
  sessions: Sessions
  share_tokens: ShareTokens
  tasks: Tasks
  users: Users
  users_organizations: UsersOrganizations
}
